version: "3"

networks:
  default:
    external:
      name: ideaware_net

services:
  ideaware-php:
    container_name: ideaware-php
    build:
      context: ../php/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../../blog:/usr/share/nginx/html/ideaware